channel_targets:
  - flatsurf main
channel_sources:
  - flatsurf,conda-forge,defaults
job:
  - release
  - release
  - style
  - test36
  - test37
action:
  - release
  - release
  - style
  - test
  - test
_python:
  - 3.6.* *_cpython
  - 3.7.* *_cpython
  - 3.7.* *_cpython
  - 3.6.* *_cpython
  - 3.7.* *_cpython
zip_keys:
  - job
  - action
  - _python
