{% set version = '1.1.0' %}
{% set build_number = '0' %}

package:
  name: cppyythonizations
  version: {{ version }}

source:
  path: ../

build:
  number: {{ build_number }}
  string: py{{ py }}_{{ build_number }}
  # cppyy is not available on Windows
  skip: True  # [win]

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
  run:
    - python
    - cppyy

test:
  imports:
    - cppyythonizations

about:
  home: https://github.com/flatsurf/cppyythonizations
  license: MIT
  license_file: COPYING
  summary: Common Pythonizations for cppyy
