{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')| string | replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER') %}
{% set action = action or 'release' %}
{% set py = _python | replace('*', '') | replace(' ', '') | replace('.', '') %}
{% set test_requirements = action in ["test", "coverage", "benchmark"] %}

package:
  name: cppyythonizations
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
{%- if action == "release" %}
  string: py{{ py }}_{{ build_number }}
{%- endif %}
  # cppyy is not available on Windows
  skip: True  # [win]
{%- if action in ["coverage", "style"] %}
  skip: True  # [not linux]
{%- endif %}

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
{%- if action == "style" %}
    - clangdev ==10.0.1
{%- endif %}
  host:
    - python {{ _python }}
    - setuptools
{%- if test_requirements %}
    - pytest
    - ruamel.yaml
    - cppyy
    - boost-cpp
    - gmp
    - valgrind >=3.15.0  # [linux]
{%- endif %}
  run:
    - python {{ _python }}
    - cppyy

{%- if action == "release" %}
test:
  imports:
    - cppyythonizations
{%- endif %}

about:
  home: https://github.com/flatsurf/cppyythonizations
  license: MIT
  license_file: COPYING
  summary: Common Pythonizations for cppyy

extra:
  recipe-maintainers:
    - saraedum
    - videlec
  variables:
    action: {{ action }}
    job: {{ job }}
