name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: "${{ matrix.on }}"
    strategy:
      matrix:
        environment: [ python-39, python-310, python-311, python-312, dev ]
        on: [ ubuntu-24.04, macos-13 ] # we do not test macos-14 yet since we don't have osx-arm64 in our pyproject.toml
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.4
      with:
        pixi-version: v0.39.5
        environments: ${{ matrix.environment }}
    - run: |
        pixi run -e ${{ matrix.environment }} test
    - run: |
        sudo apt update
        sudo apt install -y libc6-dbg
        pixi run -e ${{ matrix.environment }} test-valgrind
      if: ${{ matrix.environment == 'dev' && matrix.on == 'ubuntu-24.04' }}
    - uses: flatsurf/actions/show-logs@main
      if: ${{ always() }}
